# Generated by Django 4.2.20 on 2025-03-16 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_alter_categorie_id_alter_currency_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='descriptioon',
            new_name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('VISA', 'VISA'), ('WAVE', 'WAVE'), ('ORANGE_MONEY', 'Orange Money'), ('MASTER_CARD', 'Master Card'), ('MOBILE_MONEY', 'Mobile Money')], default='VISA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Succés'), ('pending', 'En cours'), ('failed', 'Echec'), ('refused', 'refusée')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
